name: at-all-in-one-image-builder

on:
  repository_dispatch:
    types: [trigger-at-all-in-one]
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Aliyun Docker Registry
      run: echo ${{ secrets.ALIYUN_DOCKER_REGISTRY_PASSWORD }} | docker login --username=${{ secrets.ALIYUN_DOCKER_REGISTRY_USER }} --password-stdin registry.cn-shanghai.aliyuncs.com

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} # 使用访问令牌进行身份验证

    # Read version from version.txt file and set date
    - name: Get the version and date
      id: get_version
      run: |
        echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Build, tag and push Docker image
      uses: docker/build-push-action@v5.0.0
      with:
        context: . # 使用当前目录作为上下文
        file: Dockerfile # Dockerfile的位置
        push: true # 推送镜像到阿里云镜像仓库
        tags: |
          registry.cn-shanghai.aliyuncs.com/datamini/asktable-all-in-one:${{ env.DATE }}
          registry.cn-shanghai.aliyuncs.com/datamini/asktable-all-in-one:latest
          datamini/asktable-all-in-one:latest
        platforms: linux/amd64 #,linux/arm64
        cache-from: type=gha # 启用 GitHub Actions 缓存，适用于跨工作流缓存
        cache-to: type=gha,mode=max # 启用缓存并优化构建


    - name: Execute deployment script-sh4  # 只更新重启，不提供 docker-compose.yaml 文件
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST_SH4 }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          # 进入部署目录
          cd /root/sh4/at-all-in-one/
          # 拉取最新镜像
          docker-compose pull && docker-compose down
          # 启动容器
          docker-compose up -d

    - name: Execute deployment script-sh1  # 只更新重启，不提供 docker-compose.yaml 文件
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST_SH1 }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          # 进入部署目录
          cd /root/sh1/at-enterprise-a/
          # 拉取最新镜像
          docker compose pull && docker compose down
          # 启动容器
          docker compose up -d

    - name: Save and push Docker image to Aliyun OSS
      run: |
        # 将镜像保存为 tar 文件
        docker save registry.cn-shanghai.aliyuncs.com/datamini/asktable-all-in-one -o asktable-all-in-one.tar
        # 安装 ossutil
        curl -o ossutil64 https://gosspublic.alicdn.com/ossutil/1.7.8/ossutil64
        chmod 755 ossutil64
        # 配置 ossutil 并上传 tar 文件到 OSS
        ./ossutil64 config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.OSS_ACCESS_KEY_ID }} -k ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        ./ossutil64 cp asktable-all-in-one.tar oss://${{ secrets.OSS_BUCKET }}/docker-images/asktable-all-in-one.tar -f
        echo "Docker 镜像已保存并上传到 OSS: oss://${{ secrets.OSS_BUCKET }}/docker-images/asktable-all-in-one.tar"
        # 清理临时文件
        rm -f asktable-all-in-one.tar
        rm -f ossutil64