name: at-all-in-one-image-builder

on:
  repository_dispatch:
    types: [trigger-at-all-in-one]
  push:
    branches:
      - main
    paths:
      - 'version.txt'

jobs:
  # 构建镜像阶段
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Aliyun Docker Registry
      run: echo ${{ secrets.ALIYUN_DOCKER_REGISTRY_PASSWORD }} | docker login --username=${{ secrets.ALIYUN_DOCKER_REGISTRY_USER }} --password-stdin registry.cn-shanghai.aliyuncs.com

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} # 使用访问令牌进行身份验证

    # Read version from version.txt file and set date
    - name: Get the version and date
      id: get_version
      run: |
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

    - name: Build, tag and push Docker image
      uses: docker/build-push-action@v5.0.0
      with:
        context: . # 使用当前目录作为上下文
        file: Dockerfile # Dockerfile的位置
        push: true # 推送镜像到阿里云镜像仓库
        tags: |
          registry.cn-shanghai.aliyuncs.com/datamini/asktable-all-in-one:${{ env.DATE }}
          registry.cn-shanghai.aliyuncs.com/datamini/asktable-all-in-one:${{ env.VERSION }}
          registry.cn-shanghai.aliyuncs.com/datamini/asktable-all-in-one:latest
          datamini/asktable-all-in-one:latest
        platforms: linux/amd64 #,linux/arm64
        cache-from: type=gha # 启用 GitHub Actions 缓存，适用于跨工作流缓存
        cache-to: type=gha,mode=max # 启用缓存并优化构建

  # 部署SH4阶段
  deploy-sh4:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - name: Deploy to SH4
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST_SH4 }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /root/sh4/at-all-in-one/
          docker-compose pull && docker-compose down
          docker-compose up -d

  # 部署SH1阶段
  deploy-sh1:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - name: Deploy to SH1
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST_SH1 }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /root/sh1/at-enterprise-a/
          docker compose pull && docker compose down
          docker compose up -d
  
  # 部署SH3阶段
  deploy-sh3:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - name: Deploy to SH3
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST_SH3 }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd /root/sh3/at-allinone-v2/
          docker compose pull && docker compose down
          docker compose up -d